version: '3.0'

services:
  mimicri:
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - BOT_PREFIX=${BOT_PREFIX}
      - LOG_FILE=/etc/data/output.txt
      - SQLITE_DB=/etc/data/db.sqlite
    build: poohcom1/mimicri:latest
    volumes:
      - "db:/etc/data"

volumes:
  db: